tax_portal/accounts/urls.py
from django.urls import path
from .views import (
    ClientSignUpView, CASignUpView, CustomLoginView, CustomLogoutView,
    ItrUserSignUpView, ItrUserLoginView, ClientPersonalInfoView, ItrPersonalInfoView,
    SelfDeclarationView, AcknowledgmentView,
)
from django.views.generic import TemplateView

urlpatterns = [
    path('signup/client/', ClientSignUpView.as_view(), name='client_signup'),
    path('signup/ca/', CASignUpView.as_view(), name='ca_signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/itr/', ItrUserSignUpView.as_view(), name='itr_signup'),
    path('login/itr/', ItrUserLoginView.as_view(), name='login_itr'),
    path('itr/personal-info/', ItrPersonalInfoView.as_view(), name='itr_personal_info'),
    path('client/personal-info/', ClientPersonalInfoView.as_view(), name='client_personal_info'),
    path('self-declaration/', SelfDeclarationView.as_view(), name='self_declaration'),
    path('acknowledgment/', AcknowledgmentView.as_view(), name='acknowledgment'),
]

tax_portal/ca/urls.py
from django.urls import path
from ca.views import CADashboardView, CAClientDetailView, FileReturnView, CAAcknowledgmentView

urlpatterns = [
    path('ca-dashboard/', CADashboardView.as_view(), name='ca_dashboard'),
    path('client/<int:pk>/', CAClientDetailView.as_view(), name='ca_client_detail'),
    path('file-return/', FileReturnView.as_view(), name='file_return'),
    path('acknowledgment/', CAAcknowledgmentView.as_view(), name='ca_acknowledgment'),
]

tax_portal/tax_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import home_view
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('accounts/', include('accounts.urls')),
    path('client/', include('clients.urls')),
    path('ca/', include('ca.urls')),
    path('dashboard/', include('dashboard.urls')), 
    path('tds_app/', include('tds_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tax_portal/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    ROLE_CHOICES = (
        ('client', 'Client'),
        ('ca', 'Chartered Accountant'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    assigned_ca = models.ForeignKey('self', null=True, blank=True, limit_choices_to={'role': 'ca'}, on_delete=models.SET_NULL)
    pan_number = models.CharField(max_length=10, blank=True, null=True)
    aadhar_number = models.CharField(max_length=12, blank=True, null=True)
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    bank_account = models.CharField(max_length=20, blank=True, null=True)

    def clean(self):
        from django.core.exceptions import ValidationError
        if self.pan_number and len(self.pan_number) < 10:
            raise ValidationError({'pan_number': 'PAN number must be at least 10 characters.'})
        if self.aadhar_number and len(self.aadhar_number) < 12:
            raise ValidationError({'aadhar_number': 'Aadhar number must be at least 12 characters.'})
        if self.phone_number and len(self.phone_number) < 10:
            raise ValidationError({'phone_number': 'Phone number must be at least 10 digits.'})
        if self.bank_account and len(self.bank_account) < 10:
            raise ValidationError({'bank_account': 'Bank account number must be at least 9 digits.'})
    
    def __str__(self):
        return f"{self.username} ({self.role})"


class ItrUsers(AbstractUser):
    user_id = models.CharField(max_length=150, unique=True)
    password = models.CharField(max_length=128)
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='itrusers_set',
        blank=True,
        help_text='The groups this user belongs to.',
        verbose_name='groups'
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='itrusers_set',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions'
    )
    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.user_id

tax_portal/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User, ItrUsers

class ClientSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'assigned_ca']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['assigned_ca'].queryset = User.objects.filter(role='ca')


class CASignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ItrSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'assigned_ca']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['assigned_ca'].queryset = User.objects.filter(role='ca')


class ItrLoginForm(UserCreationForm):
    pass
class LoginForm(AuthenticationForm):
    pass


class ItrUserSignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = ItrUsers
        fields = ['user_id', 'password']


class ItrUserLoginForm(forms.Form):
    user_id = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    FIN_YEAR_CHOICES = [
        (f"{y}-{y+1}", f"{y}-{y+1}") for y in range(2024, 2026)
    ]
    financial_year = forms.ChoiceField(choices=FIN_YEAR_CHOICES, label="Financial Year")


class ClientPersonalInfoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial', {})
        instance = kwargs.get('instance', None)
        if instance:
            initial.update({
                'pan_number': instance.pan_number,
                'aadhar_number': instance.aadhar_number,
                'phone_number': instance.phone_number,
                'address': instance.address,
                'bank_account': instance.bank_account,
            })
            kwargs['initial'] = initial
        super().__init__(*args, **kwargs)
    class Meta:
        model = User
        fields = ['pan_number', 'aadhar_number', 'phone_number', 'address', 'bank_account']
        widgets = {
            'pan_number': forms.TextInput(attrs={'class': 'w-full border rounded px-3 py-2'}),
            'aadhar_number': forms.TextInput(attrs={'class': 'w-full border rounded px-3 py-2'}),
            'phone_number': forms.TextInput(attrs={'class': 'w-full border rounded px-3 py-2'}),
            'address': forms.TextInput(attrs={'class': 'w-full border rounded px-3 py-2'}),
            'bank_account': forms.TextInput(attrs={'class': 'w-full border rounded px-3 py-2'}),
        }

tax_portal/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView, TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from .models import User, ItrUsers
from .forms import ClientSignUpForm, CASignUpForm, LoginForm, ItrUserSignUpForm, ItrUserLoginForm, ClientPersonalInfoForm
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.crypto import get_random_string
from django.utils import timezone
from django.shortcuts import render
from clients.models import FiledReturn
from datetime import date
from accounts.models import User


class ClientSignUpView(CreateView):
    model = User
    form_class = ClientSignUpForm
    template_name = 'accounts/client_signup.html'
    success_url = reverse_lazy('client_personal_info')

    def form_valid(self, form):
        form.instance.role = 'client'
        response = super().form_valid(form)
        login(self.request, self.object) 
        return response


class CASignUpView(CreateView):
    model = User
    form_class = CASignUpForm
    template_name = 'accounts/ca_signup.html'
    success_url = reverse_lazy('ca_dashboard')

    def form_valid(self, form):
        form.instance.role = 'ca'
        response = super().form_valid(form)
        login(self.request, self.object)  
        return response


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get_success_url(self):
        user = self.request.user
        if user.role == 'client':
            return reverse_lazy('client_dashboard')
        elif user.role == 'ca':
            return reverse_lazy('ca_dashboard')
        return reverse_lazy('home')


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('home')


class ItrUserSignUpView(CreateView):
    model = ItrUsers
    form_class = ItrUserSignUpForm
    template_name = 'accounts/itr_signup.html'
    success_url = reverse_lazy('login_itr')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.username = form.cleaned_data['user_id']
        user.save()
        return super().form_valid(form)


class ItrUserLoginView(FormView):
    template_name = 'accounts/itr_login.html'
    form_class = ItrUserLoginForm

    def get_success_url(self):
        client_id = self.request.GET.get('client_id')
        if client_id:
            return reverse_lazy('itr_personal_info') + f'?client_id={client_id}'
        return reverse_lazy('itr_personal_info')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_id = self.request.GET.get('client_id') or self.request.POST.get('client_id')
        context['client_id'] = client_id
        return context

    def form_valid(self, form):
        user_id = form.cleaned_data['user_id']
        password = form.cleaned_data['password']
        financial_year = form.cleaned_data['financial_year']
        client_id = self.request.GET.get('client_id') or self.request.POST.get('client_id')
        user = authenticate(self.request, username=user_id, password=password)
        if user is not None:
            login(self.request, user)
            self.request.session['financial_year'] = financial_year
            if client_id:
                self.request.session['ack_client_id'] = int(client_id)
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class ClientPersonalInfoView(LoginRequiredMixin, FormView):
    template_name = 'accounts/client_personal_info.html'
    form_class = ClientPersonalInfoForm
    success_url = reverse_lazy('login')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        user.pan_number = form.cleaned_data['pan_number']
        user.aadhar_number = form.cleaned_data['aadhar_number']
        user.phone_number = form.cleaned_data['phone_number']
        user.address = form.cleaned_data['address']
        user.bank_account = form.cleaned_data['bank_account']
        user.save()
        return super().form_valid(form)


class ItrPersonalInfoView(LoginRequiredMixin, FormView):
    template_name = 'accounts/itr_personal_info.html'
    form_class = ClientPersonalInfoForm
    success_url = reverse_lazy('itr_personal_info')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        client_id = self.request.GET.get('client_id') or self.request.POST.get('client_id')
        if client_id:
            try:
                client = User.objects.get(id=client_id)
                kwargs['instance'] = client
            except User.DoesNotExist:
                kwargs['instance'] = self.request.user
        else:
            kwargs['instance'] = self.request.user
        return kwargs

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or request.user.role != 'ca':
            from django.contrib.auth.views import redirect_to_login
            return redirect_to_login(request.get_full_path())
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user
        user.pan_number = form.cleaned_data['pan_number']
        user.aadhar_number = form.cleaned_data['aadhar_number']
        user.phone_number = form.cleaned_data['phone_number']
        user.address = form.cleaned_data['address']
        user.bank_account = form.cleaned_data['bank_account']
        user.save()
        return super().form_valid(form)


class SelfDeclarationView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/self_declaration.html'

    def post(self, request, *args, **kwargs):
        client_id = request.GET.get('client_id') or request.POST.get('client_id')
        if client_id:
            client = get_object_or_404(User, id=client_id)
            due_date = date(2025, 7, 30)
            FiledReturn.objects.get_or_create(
                client=client,
                return_type='IT',
                due_date=due_date,
                defaults={'filed_by': request.user}
            )
            request.session['ack_client_id'] = int(client_id)
        if 'ack_due_date' in request.session:
            del request.session['ack_due_date']
        return redirect('acknowledgment')


class AcknowledgmentView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/acknowledgment.html'

    def get(self, request, *args, **kwargs):
        from accounts.models import User
        from clients.models import FiledReturn
        client_id = request.session.get('ack_client_id') or request.GET.get('client_id')
        user = None
        if client_id:
            try:
                user = User.objects.get(id=client_id)
                due_date = date(2025, 7, 30)
                FiledReturn.objects.get_or_create(
                    client=user,
                    return_type='IT',
                    due_date=due_date,
                    defaults={'filed_by': request.user}
                )
            except User.DoesNotExist:
                user = None
        context = {
            'assessment_year': '2025-26',
            'name': user.get_full_name() or user.username if user else '',
            'pan': getattr(user, 'pan_number', '') if user else '',
            'building': 'Sunshine Apartments',
            'street': 'MG Road',
            'area': 'MG Road',
            'city': 'Bengaluru',
            'state': 'Karnataka',
            'pincode': '560097',
            'status': 'Filed',
            'ack_number': get_random_string(12).upper(),
            'gross_total_income': '12,50,000',
            'deductions': '1,50,000',
            'total_income': '11,00,000',
            'deemed_income': '0',
            'current_year_loss': '0',
            'net_tax_payable': '1,10,000',
            'interest_fee': '2,000',
            'total_tax_interest_fee': '1,12,000',
            'advance_tax': '50,000',
            'tds': '40,000',
            'tcs': '5,000',
            'self_assessment_tax': '10,000',
            'total_taxes_paid': '1,05,000',
            'tax_payable': '7,000',
            'refund': '0',
            'exempt_income': '1,00,000',
        }
        return render(request, self.template_name, context)

tax_portal/accounts/templates/accounts/acknowledgment.html
{% extends "base.html" %}
{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-3xl w-full border-t-8 border-gold-400">
    <h1 class="text-2xl font-extrabold text-blue-900 mb-6 text-center">ITR-V Acknowledgment Form</h1>
    <div class="border border-gray-300 rounded-xl p-6 bg-gray-50">
      <div class="flex justify-between mb-4">
        <span class="font-bold">Assessment Year: {{ assessment_year }}</span>
        <span class="font-bold">Form: ITR-V</span>
      </div>
      <table class="w-full text-sm mb-6">
        <tr><td class="font-semibold">Name</td><td>{{name}}</td><td class="font-semibold">PAN</td><td>{{ pan }}</td></tr>
        <tr><td class="font-semibold">Flat No</td><td>12B</td><td class="font-semibold">House Name</td><td>Sunshine Apartments</td></tr>
        <tr><td class="font-semibold">Street</td><td>MG Road</td><td class="font-semibold">Area/Locality</td><td>Central Bank</td></tr>
        <tr><td class="font-semibold">Town/City/District</td><td>Bengaluru</td><td class="font-semibold">State</td><td>Karnataka</td></tr>
        <tr><td class="font-semibold">Pin/ZipCode</td><td>400001</td><td class="font-semibold">Status</td><td>Filed</td></tr>
        <tr><td colspan="4"><hr class="my-2"></td></tr>
        <tr><td class="font-semibold">Acknowledgement Number</td><td colspan="3">{{ ack_number }}</td></tr>
      </table>
      <h2 class="font-bold text-lg mb-2">Computation of Income and Tax</h2>
      <table class="w-full text-sm mb-6 border">
        <tr class="bg-blue-50"><th class="p-1">#</th><th class="p-1">Particulars</th><th class="p-1">Amount</th></tr>
        <tr><td>1</td><td>Gross Total Income</td><td>12,50,000</td></tr>
        <tr><td>2</td><td>Total Deductions under Chapter-VI-A</td><td>1,50,000</td></tr>
        <tr><td>3</td><td>Total Income</td><td>11,00,000</td></tr>
        <tr><td>3a</td><td>Deemed Total Income under AMT/MAT</td><td>0</td></tr>
        <tr><td>3b</td><td>Current Year loss, if any</td><td>0</td></tr>
        <tr><td>4</td><td>Net Tax Payable</td><td>1,10,000</td></tr>
        <tr><td>5</td><td>Interest and Fee Payable</td><td>2,000</td></tr>
        <tr><td>6</td><td>Total Tax, Interest and Fee Payable</td><td>1,12,000</td></tr>
        <tr><td>7</td><td>Taxes Paid</td><td></td></tr>
        <tr><td>7a</td><td>Advance Tax</td><td>50,000</td></tr>
        <tr><td>7b</td><td>TDS</td><td>40,000</td></tr>
        <tr><td>7c</td><td>TCS</td><td>5,000</td></tr>
        <tr><td>7d</td><td>Self Assessment Tax</td><td>10,000</td></tr>
        <tr><td>7e</td><td>Total Taxes Paid (7a+7b+7c+7d)</td><td>1,05,000</td></tr>
        <tr><td>8</td><td>Tax Payable (6-7e)</td><td>7,000</td></tr>
        <tr><td>9</td><td>Refund (7e-6)</td><td>0</td></tr>
        <tr><td>10</td><td>Exempt Income</td><td>1,00,000</td></tr>
      </table>
      <div class="mt-6">
        <h2 class="font-bold text-lg mb-2">Verification</h2>
        <p class="text-gray-700">I, <span class="font-semibold">{{ name }}</span>, verify that the information given above is true and correct to the best of my knowledge and belief.</p>
      </div>
    </div>
    <div class="mt-8 text-center">
      {% if request.user.role == 'client' %}
        <a href="/client/dashboard/" class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-6 rounded-xl font-semibold shadow">Back to Dashboard</a>
      {% elif request.user.role == 'ca' %}
        <a href="/ca/ca-dashboard/" class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-6 rounded-xl font-semibold shadow">Back to Dashboard</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

tax_portal/accounts/templates/accounts/ca_signup.html
{% extends 'base.html' %}

{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-md w-full border-t-8 border-gold-400">
    <h2 class="text-3xl font-extrabold text-blue-900 mb-6 text-center">CA Signup</h2>
    <form method="post" class="space-y-6" novalidate>
      {% csrf_token %}
      {% for field in form %}
        <div>
          {{ field.label_tag }}
          {{ field }}
          {% if field.errors %}
            <div class="text-red-600 text-sm mt-1">{{ field.errors|striptags }}</div>
          {% endif %}
        </div>
      {% endfor %}
      <button type="submit" class="w-full bg-gold-400 hover:bg-gold-500 text-blue-900 py-3 rounded-xl font-semibold text-lg shadow">Sign Up</button>
    </form>
  </div>
</div>
{% endblock %}

tax_portal/accounts/templates/accounts/client_personal_info.html
{% extends "base.html" %}
{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-2xl w-full border-t-8 border-gold-400">
    <h2 class="text-2xl font-extrabold text-blue-900 mb-6 text-center">Personal Information</h2>
    <form method="post" class="space-y-6">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="w-full bg-blue-700 hover:bg-blue-800 text-white py-3 rounded-xl font-semibold text-lg shadow">Save</button>
    </form>
  </div>
</div>
{% endblock %}

tax_portal/accounts/templates/accounts/client_signup.html
{% extends 'base.html' %}

{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-md w-full border-t-8 border-gold-400">
    <h2 class="text-3xl font-extrabold text-blue-900 mb-6 text-center">Client Signup</h2>
    <form method="post" class="space-y-6" novalidate>
      {% csrf_token %}
      {% for field in form %}
        <div>
          {{ field.label_tag }}
          {{ field }}
          {% if field.errors %}
            <div class="text-red-600 text-sm mt-1">{{ field.errors|striptags }}</div>
          {% endif %}
        </div>
      {% endfor %}
      <button type="submit" class="w-full bg-gold-400 hover:bg-gold-500 text-blue-900 py-3 rounded-xl font-semibold text-lg shadow">Sign Up</button>
    </form>
  </div>
</div>
{% endblock %}

tax_portal/accounts/templates/accounts/itr_login.html
{% extends "base.html" %}
{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-md w-full border-t-8 border-gold-400">
    <h1 class="text-3xl font-extrabold text-blue-900 mb-6 text-center">ITR User Login</h1>
    <form method="post" class="space-y-6">
      {% csrf_token %}
      {% if client_id %}
        <input type="hidden" name="client_id" value="{{ client_id }}">
      {% endif %}
      <div>
        <label for="id_user_id" class="block text-gray-700 font-semibold mb-1">ITR User ID</label>
        {{ form.user_id }}
      </div>
      <div>
        <label for="id_password" class="block text-gray-700 font-semibold mb-1">Password</label>
        {{ form.password }}
      </div>
      <div>
        <label for="id_financial_year" class="block text-gray-700 font-semibold mb-1">Financial Year</label>
        {{ form.financial_year }}
      </div>
      <button type="submit" class="w-full bg-blue-700 hover:bg-blue-800 text-white py-3 rounded-xl font-semibold text-lg shadow">Login</button>
    </form>
  </div>
</div>
{% endblock %}

tax_portal/accounts/templates/accounts/itr_signup.html
{% extends "base.html" %}
{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-md w-full border-t-8 border-gold-400">
    <h1 class="text-3xl font-extrabold text-blue-900 mb-6 text-center">ITR User Sign Up</h1>
    <form method="post" class="space-y-6">
      {% csrf_token %}
      <div>
        <label for="id_user_id" class="block text-gray-700 font-semibold mb-1">ITR User ID</label>
        {{ form.user_id }}
      </div>
      <div>
        <label for="id_password" class="block text-gray-700 font-semibold mb-1">Password</label>
        {{ form.password }}
      </div>
      <button type="submit" class="w-full bg-gold-400 hover:bg-gold-500 text-blue-900 py-3 rounded-xl font-semibold text-lg shadow">Sign Up</button>
    </form>
  </div>
</div>
{% endblock %}

tax_portal/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-md w-full border-t-8 border-gold-400">
    <h2 class="text-3xl font-extrabold text-blue-900 mb-6 text-center">Login</h2>
    <form method="post" class="space-y-6">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="w-full bg-blue-700 hover:bg-blue-800 text-white py-3 rounded-xl font-semibold text-lg shadow">Login</button>
    </form>
  </div>
</div>
{% endblock %}

tax_portal/accounts/templates/accounts/self_declaration.html
{% extends "base.html" %}
{% block content %}
<div class="flex items-center justify-center min-h-[80vh] bg-gradient-to-br from-blue-50 to-white">
  <div class="bg-white/95 shadow-2xl rounded-3xl p-10 max-w-xl w-full border-t-8 border-gold-400">
    <h1 class="text-2xl font-extrabold text-blue-900 mb-6 text-center">Self Declaration</h1>
    <form method="post" class="space-y-6">
      {% csrf_token %}
      <div class="mb-6 text-left">
        <label class="flex items-center space-x-2">
          <input type="checkbox" name="declaration" required class="form-checkbox h-5 w-5 text-blue-600">
          <span class="text-gray-700">I hereby declare that the information provided is true and correct to the best of my knowledge and belief.</span>
        </label>
      </div>
      <button type="submit" class="w-full bg-gold-400 hover:bg-gold-500 text-blue-900 py-3 rounded-xl font-semibold text-lg shadow">Submit</button>
    </form>
  </div>
</div>
{% endblock %}